import Navbar from '@/components/navbar'
import './globals.css'

export const metadata = {
  title: 'Movie-app (🏗️development phase)',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-gradient-to-t from-black to-neutral-600'>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
