import Navbar from '@/components/navbar'
import './globals.css'

export const metadata = {
  title: 'test-app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-gradient-to-r from-black via-neutral-700 to-gray-700'>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
